features:
  account: true
  client: true

---

spring:
  profiles.active: qa
  jpa.properties.hibernate.generate_statistics: true

server:
  port: 8080
  servlet.context-path: /dbo
  tomcat:
    mbeanregistry.enabled: true
    threads.max: 100

management:
  metrics:
    enable.all: true
    web.server.request.autotime.enabled: true
  endpoints.web.exposure.include: '*'
  endpoint.shutdown.enabled: true

httpPool:
  maxTotal: 100
  defaultMaxPerRoute: 10
  connectTimeout: 5000
  connectionRequestTimeout: 1000
  socketTimeout: 65000
  validateAfterInactivity: 2000

---

spring:
  config.activate.on-profile: test
  main.lazy-initialization: true
  autoconfigure.exclude:
    - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
    - org.springframework.boot.autoconfigure.jdbc.DataSourceTransactionManagerAutoConfiguration
    - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration

---

spring:
  config.activate.on-profile: it
  integration.legacyAccountingSystem:
    baseUrl: "http://localhost:8888/api"
    accountsEndpoint: "/account"
  main.lazy-initialization: true
  datasource:
    driverClassName: org.apache.derby.jdbc.EmbeddedDriver
    url: jdbc:derby:memory:dbo-db;create=true
    username: APP
    password: APP
    hikari:
      poolName: hikari-connection-pool
      maximumPoolSize: 2
      minimumIdle: 1
  jpa:
    show-sql: true
    hibernate.ddl-auto: validate
  liquibase: #https://javadeveloperzone.com/spring-boot/spring-boot-liquibase-example/
    enabled: true
    contexts: prod, qa
    change-log: classpath:/db-changelog.xml
    liquibaseSchema: liquibase
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}

---

spring:
  config.activate.on-profile: qa
  integration.legacyAccountingSystem:
    baseUrl: "http://localhost:8888/api"
    accountsEndpoint: "/account"
  datasource:
    driverClassName: org.apache.derby.jdbc.EmbeddedDriver
    url: jdbc:derby:dbo-db;create=true
    username: APP
    password: APP
    hikari:
      poolName: hikari-connection-pool
      maximumPoolSize: 5
      minimumIdle: 1
      idleTimeout: 600000
  jpa:
    show-sql: true
    hibernate.ddl-auto: validate
  liquibase:
    enabled: true
    contexts: prod, qa
    change-log: classpath:/db-changelog.xml
    liquibaseSchema: liquibase
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    rollback-file: liquibase-rollback.sql
    test-rollback-on-update: true

---

spring:
  config.activate.on-profile: preprod
  integration.legacyAccountingSystem:
    baseUrl: #should by externalized
    accountsEndpoint: "/account"
  sql.init:
    platform: postgres
    mode: always
  datasource:
    driverClassName: org.postgresql.Driver
    url:  #should by externalized
    username: #should by externalized
    password: #should by externalized
    hikari:
      poolName: hikari-connection-pool
      maximumPoolSize: 10
      minimumIdle: 2
      idleTimeout: 1800000
  jpa.hibernate.ddl-auto: validate
  liquibase:
    enabled: true
    contexts: prod, qa
    change-log: classpath:/db-changelog.xml
    liquibaseSchema: liquibase
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    rollback-file: liquibase-rollback.sql
    test-rollback-on-update: true

---

spring:
  config.activate.on-profile: prod
  integration.legacyAccountingSystem:
    baseUrl: "http://localhost:8888/api"
    accountsEndpoint: "/account"
  sql.init:
    platform: postgres
    mode: always
  datasource:
    driverClassName: org.postgresql.Driver
    url: #should by externalized
    username: #should by externalized
    password: #should by externalized
    hikari:
      poolName: hikari-connection-pool
      maximumPoolSize: 10
      minimumIdle: 2
      idleTimeout: 1800000
  jpa.hibernate.ddl-auto: validate
  liquibase:
    enabled: true
    contexts: prod
    change-log: classpath:/db-changelog.xml
    liquibaseSchema: liquibase
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    rollback-file: liquibase-rollback.sql
    test-rollback-on-update: true
